[target.'cfg(all(feature = "evalboard", target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32U031R8Ix"

[target.'cfg(all(feature = "sample_1", target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32U031C8Tx"


[build]
target = "thumbv6m-none-eabi"

[env]
DEFMT_LOG = "debug"